#####################################################
# https://github.com/vargaloid                      #
# Install zabbix-agent-4.0                          #
# For CentOS7; Debian 8, 9, 10; Ubuntu 16.04, 18.04 #
# Version 0.07                                      #
#####################################################
---
- hosts: demo
  become: yes
  user: ansible
  vars:
    zbx_srv: 192.168.0.1
    centos7_link: https://repo.zabbix.com/zabbix/4.4/rhel/7/x86_64/zabbix-release-4.4-1.el7.noarch.rpm
   
  roles:
    - zabbix

    
