---
- hosts: demo
  become: yes
#  remote_user: USERNAME
  vars:
    zbx_srv: 192.168.3.1
    centos7_link: https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm
  roles:
    - zabbix.agent
