--- # My Loops Playbook
- hosts: demo
  user: ansible
  become: yes
  connection: ssh
  tasks:
          - name: add list of users in my nodes
            user: name='{{item}}' state=present
            with_items:
                    - Hiren
                    - Marvin
                    - Shawn
                    - Nick
                    - Shane

