--- # Zabbix Playbook
- hosts: demo
  user: ansible
  become: yes
  connection: ssh
  tasks:
          - name: Installing Repo and Packages
            yum:
              name: https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm
              state: present
              validate_certs: false
          - name: Installing zabbix agent
            yum:
              name: zabbix-agent
              state: present
          


        
